/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Created:		Aug 16, 2022
 *			ec2-user <ec2-user@ip-172-31-29-226.us-west-2.compute.internal>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"        SUMMARY OF THE HDF5 CONFIGURATION\n"
	"        =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.12.2\n"
	"                  Configured on: 2022-08-16\n"
	"                  Configured by: Ninja\n"
	"                    Host system: Darwin-21.5.0\n"
	"              Uname information: Darwin\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /Users/ec2-user/vcpkg/packages/hdf5_arm64-osx/debug\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: Debug\n"
	"              Debugging Symbols: OFF\n"
	"                        Asserts: OFF\n"
	"                      Profiling: OFF\n"
	"             Optimization Level: OFF\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: \n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: m;dl\n"
	"                       Archiver: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar\n"
	"                         Ranlib: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: YES\n"
	"                     C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 13.1.6.13160021\n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"                         CFLAGS:  -std=c99 -fPIC\n"
	"                      H5_CFLAGS: -Wall;-Warray-bounds;-Wcast-qual;-Wconversion;-Wdouble-promotion;-Wextra;-Wformat=2;-Wframe-larger-than=16384;-Wimplicit-fallthrough;-Wnull-dereference;-Wunused-const-variable;-Wwrite-strings;-Wpedantic;-Wvolatile-register-var;-Wno-c++-compat;-Wbad-function-cast;-Wimplicit-function-declaration;-Wincompatible-pointer-types;-Wmissing-declarations;-Wpacked;-Wshadow;-Wswitch;-Wno-error=incompatible-pointer-types-discards-qualifiers;-Wunused-function;-Wunused-variable;-Wunused-parameter;-Wcast-align;-Wformat;-Wno-missing-noreturn\n"
	"                      AM_CFLAGS: \n"
	"               Shared C Library: NO\n"
	"               Static C Library: YES\n"
	"\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler:  \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: NO\n"
	"         Static Fortran Library: YES\n"
	"\n"
	"                            C++: OFF\n"
	"                   C++ Compiler:  \n"
	"                      C++ Flags: \n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: NO\n"
	"             Static C++ Library: YES\n"
	"\n"
	"                            JAVA: OFF\n"
	"                 JAVA Compiler:  \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                     Parallel HDF5: OFF\n"
	"  Parallel Filtered Dataset Writes: \n"
	"                Large Parallel I/O: \n"
	"                High-level library: ON\n"
	"Dimension scales w/ new references: \n"
	"                  Build HDF5 Tests: OFF\n"
	"                  Build HDF5 Tools: OFF\n"
	"       Build High-level HDF5 Tools: \n"
	"                      Threadsafety: OFF\n"
	"               Default API mapping: v112\n"
	"    With deprecated public symbols: ON\n"
	"            I/O filters (external):  DEFLATE ENCODE\n"
	"                               MPE: \n"
	"                        Direct VFD: \n"
	"                        Mirror VFD: \n"
	"                (Read-Only) S3 VFD: \n"
	"              (Read-Only) HDFS VFD: \n"
	"                           dmalloc: \n"
	"    Packages w/ extra debug output: \n"
	"                       API Tracing: OFF\n"
	"              Using memory checker: OFF\n"
	"   Memory allocation sanity checks: OFF\n"
	"            Function Stack Tracing: OFF\n"
	"                  Use file locking: best-effort\n"
	"         Strict File Format Checks: OFF\n"
	"      Optimization Instrumentation: \n"
;

